title = "VanGo SSG"
description = "A fast and modern static site generator built with Go"
baseURL = "http://localhost:1313/"
language = "en"
author = "<van_go/>"

# Directory paths
contentDir = "content"
layoutDir = "layouts"
staticDir = "static"
publicDir = "public"

# Build settings
buildDrafts = false
buildFuture = false
cleanBuild = true

# Server settings
port = 1313
host = "localhost"
liveReload = true

# Custom parameters
[params]
    description = "Welcome to my VanGo-powered website"
    version = "1.0.0"
    social = { twitter = "@username", github = "username" }
